"""Base class for real-time pattern detectors."""

from __future__ import annotations

from abc import ABC, abstractmethod
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ...models import Message
    from ..alerts.models import Alert
    from ..state import SessionState


class PatternDetector(ABC):
    """Base class for real-time pattern detectors.

    Each detector implements a specific waste pattern detection algorithm
    that works WITHOUT embeddings (using only string matching, regex,
    counters, and state tracking).
    """

    def __init__(self, config: dict):
        """Initialize detector with configuration."""
        self.config = config

    @abstractmethod
    def process_message(
        self, message: "Message", state: "SessionState"
    ) -> list["Alert"]:
        """Analyze message and return alerts if pattern detected.

        Args:
            message: The assistant or user message to analyze
            state: Current session state (will be mutated by detector)

        Returns:
            List of alerts generated by this detector (empty if no pattern found)
        """
        pass

    @abstractmethod
    def get_default_config(self) -> dict:
        """Return default configuration parameters."""
        pass

    @property
    @abstractmethod
    def pattern_name(self) -> str:
        """Unique pattern identifier."""
        pass
