"""TER real-time monitoring client - main user-facing API."""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Callable

from ...models import ContentBlock, Message, TokenUsage
from ..alerts.models import Alert
from ..detectors import get_enabled_detectors
from ..engine import RealtimeEngine

logger = logging.getLogger(__name__)


class TERMonitor:
    """Main client for real-time TER monitoring.

    Example usage:
        monitor = TERMonitor(on_alert=lambda alert: print(alert.suggestion))
        session = monitor.start_session()
        session.add_assistant_message(response)
        final_report = session.end()
    """

    def __init__(
        self,
        config: dict | None = None,
        config_path: Path | str | None = None,
        on_alert: Callable[[Alert], None] | None = None,
    ):
        """Initialize TER monitor.

        Args:
            config: Configuration dictionary. If None, uses default config.
            config_path: Path to config YAML file (not implemented yet)
            on_alert: Optional callback function called for each alert
        """
        self.config = config or self._get_default_config()
        self.on_alert_callback = on_alert

        # Store learning config for sessions
        self.learning_config = self.config.get("learning", {})

        # Initialize detectors based on config
        patterns_config = self.config.get("patterns", {})
        detectors = get_enabled_detectors(patterns_config)

        # Create engine
        self.engine = RealtimeEngine(detectors=detectors)

        logger.info(f"TERMonitor initialized with {len(detectors)} detectors")

    def start_session(self, session_id: str | None = None) -> "TERSession":
        """Start a new monitoring session.

        Args:
            session_id: Optional custom session ID

        Returns:
            TERSession object for tracking this session
        """
        state = self.engine.start_session(session_id)
        return TERSession(self.engine, state.session_id, self.on_alert_callback)

    @staticmethod
    def _get_default_config() -> dict:
        """Get default configuration when no config provided."""
        return {
            "patterns": {
                "duplicate_tool_calls": {"enabled": True, "window_size": 5},
                "repetitive_reads": {"enabled": True, "min_reads": 3},
                "edit_fragmentation": {"enabled": True, "min_consecutive": 3},
                "bash_antipatterns": {"enabled": True},
                "failed_tool_retries": {"enabled": True},
            },
            "learning": {
                "enabled": True,
                "auto_adjust_thresholds": True,
                "min_sessions_before_adjust": 5,
                "target_precision": 0.80,
                "target_recall": 0.70,
                "max_adjustment_per_session": 1,
            },
        }


class TERSession:
    """Represents a single monitoring session.

    Provides methods to feed messages and retrieve alerts.
    """

    def __init__(
        self,
        engine: RealtimeEngine,
        session_id: str,
        on_alert_callback: Callable[[Alert], None] | None = None,
    ):
        """Initialize session.

        Args:
            engine: The RealtimeEngine instance
            session_id: Session identifier
            on_alert_callback: Optional callback for alerts
        """
        self.engine = engine
        self.session_id = session_id
        self.on_alert_callback = on_alert_callback

    def add_assistant_message(self, response: dict | object) -> list[Alert]:
        """Process an assistant message through real-time detection.

        Args:
            response: Either a dict (from Anthropic API) or any object with
                     .id, .role, .content, .usage, .stop_reason attributes

        Returns:
            List of alerts generated by this message
        """
        # Convert to Message object
        message = self._convert_to_message(response, role="assistant")

        # Process through engine
        alerts = self.engine.process_message(self.session_id, message)

        # Call user callback if provided
        if self.on_alert_callback:
            for alert in alerts:
                try:
                    self.on_alert_callback(alert)
                except Exception as e:
                    logger.error(f"Alert callback failed: {e}", exc_info=True)

        return alerts

    def add_user_message(self, user_message: dict | list) -> list[Alert]:
        """Process a user message (mainly for tool_result blocks).

        Args:
            user_message: Either a dict with content blocks or a list of content blocks

        Returns:
            List of alerts generated by this message
        """
        # Convert to Message object
        message = self._convert_to_message(user_message, role="user")

        # Process through engine
        alerts = self.engine.process_message(self.session_id, message)

        # Call user callback if provided
        if self.on_alert_callback:
            for alert in alerts:
                try:
                    self.on_alert_callback(alert)
                except Exception as e:
                    logger.error(f"Alert callback failed: {e}", exc_info=True)

        return alerts

    def add_tool_result(self, tool_use_id: str, content: str, is_error: bool = False):
        """Convenience method to add a single tool result.

        Args:
            tool_use_id: ID of the tool use block this result corresponds to
            content: Result content
            is_error: Whether this is an error result
        """
        # Create a user message with single tool_result block
        user_message = {
            "role": "user",
            "content": [
                {
                    "type": "tool_result",
                    "tool_use_id": tool_use_id,
                    "content": content,
                    "is_error": is_error,
                }
            ],
        }
        return self.add_user_message(user_message)

    def has_critical_alerts(self) -> bool:
        """Check if session has any critical severity alerts."""
        state = self.engine.sessions.get(self.session_id)
        if not state:
            return False

        return any(alert.severity.value == "critical" for alert in state.alerts)

    def get_recent_alerts(
        self, count: int = 5, severity: str | None = None
    ) -> list[Alert]:
        """Get most recent alerts from this session.

        Args:
            count: Number of alerts to return
            severity: Optional filter by severity ("info", "warning", "critical")

        Returns:
            List of recent alerts
        """
        state = self.engine.sessions.get(self.session_id)
        if not state:
            return []

        alerts = state.alerts
        if severity:
            alerts = [
                a for a in alerts if a.severity.value == severity
            ]

        return alerts[-count:]

    def get_all_alerts(self) -> list[Alert]:
        """Get all alerts from this session."""
        state = self.engine.sessions.get(self.session_id)
        if not state:
            return []
        return state.alerts

    def get_status(self) -> dict:
        """Get current session metrics."""
        return self.engine.get_status(self.session_id)

    def end(
        self,
        run_posthoc_analysis: bool = False,
        enable_learning: bool = True,
        learning_config: dict | None = None,
    ) -> dict:
        """End the session and optionally run post-hoc analysis.

        Args:
            run_posthoc_analysis: If True, runs full TER analysis with embeddings
            enable_learning: If True, uses feedback to adjust thresholds
            learning_config: Optional learning config override

        Returns:
            Dictionary with final session metrics and learning results
        """
        # Get final status and all alerts before ending
        status = self.get_status()
        all_alerts = self.get_all_alerts()

        # End session and get JSONL snapshot
        snapshot_path = self.engine.end_session(self.session_id)

        result = {
            **status,
            "snapshot_path": str(snapshot_path),
        }

        if run_posthoc_analysis:
            try:
                # Import learning components
                from ..learning import (
                    AdaptiveThresholdLearner,
                    FeedbackMetrics,
                    PostHocAnalyzer,
                )

                # Run post-hoc analysis
                logger.info("Running post-hoc analysis with embeddings...")
                analyzer = PostHocAnalyzer()
                posthoc_result = analyzer.analyze_session(snapshot_path)

                result["posthoc_ter"] = posthoc_result.aggregate_ter
                result["posthoc_waste_tokens"] = sum(
                    p.tokens_wasted for p in posthoc_result.waste_patterns
                )
                result["posthoc_pattern_count"] = len(posthoc_result.waste_patterns)

                # Learning loop
                if enable_learning:
                    logger.info("Running learning feedback loop...")

                    # Use provided learning config or defaults
                    if learning_config is None:
                        learning_config = {
                            "auto_adjust_thresholds": True,
                            "min_sessions_before_adjust": 5,
                            "target_precision": 0.80,
                            "target_recall": 0.70,
                            "max_adjustment_per_session": 1,
                        }

                    # Compute feedback metrics
                    metrics = FeedbackMetrics.compute(all_alerts, posthoc_result)
                    result["feedback_metrics"] = metrics.to_dict()

                    # Adaptive learning
                    learner = AdaptiveThresholdLearner()
                    adjustments = learner.learn_from_session(
                        all_alerts, posthoc_result, learning_config
                    )

                    result["threshold_adjustments"] = adjustments
                    result["learning_summary"] = learner.get_learning_summary()

                    logger.info(f"Learning complete. Adjustments: {adjustments}")

            except Exception as e:
                logger.error(f"Post-hoc analysis/learning failed: {e}", exc_info=True)
                result["posthoc_error"] = str(e)

        return result

    def _convert_to_message(self, data: dict | object, role: str) -> Message:
        """Convert API response or dict to Message object."""
        import uuid
        from datetime import datetime

        # Handle dict format (from Anthropic API)
        if isinstance(data, dict):
            msg_id = data.get("id", str(uuid.uuid4()))
            content = data.get("content", [])
            usage_data = data.get("usage")
            stop_reason = data.get("stop_reason")
        else:
            # Handle object with attributes
            msg_id = getattr(data, "id", str(uuid.uuid4()))
            content = getattr(data, "content", [])
            usage_data = getattr(data, "usage", None)
            stop_reason = getattr(data, "stop_reason", None)

        # Convert content blocks
        content_blocks = []
        for block in content:
            if isinstance(block, dict):
                content_blocks.append(
                    ContentBlock(
                        block_type=block.get("type", "text"),
                        text=block.get("text") or block.get("content"),
                        tool_name=block.get("name"),
                        tool_input=block.get("input"),
                        tool_use_id=block.get("id") or block.get("tool_use_id"),
                    )
                )
            else:
                # Handle object
                content_blocks.append(
                    ContentBlock(
                        block_type=getattr(block, "type", "text"),
                        text=getattr(block, "text", None)
                        or getattr(block, "content", None),
                        tool_name=getattr(block, "name", None),
                        tool_input=getattr(block, "input", None),
                        tool_use_id=getattr(block, "id", None)
                        or getattr(block, "tool_use_id", None),
                    )
                )

        # Convert usage
        usage = None
        if usage_data:
            if isinstance(usage_data, dict):
                usage = TokenUsage(
                    input_tokens=usage_data.get("input_tokens", 0),
                    output_tokens=usage_data.get("output_tokens", 0),
                    cache_creation_input_tokens=usage_data.get(
                        "cache_creation_input_tokens", 0
                    ),
                    cache_read_input_tokens=usage_data.get("cache_read_input_tokens", 0),
                )
            else:
                usage = TokenUsage(
                    input_tokens=getattr(usage_data, "input_tokens", 0),
                    output_tokens=getattr(usage_data, "output_tokens", 0),
                    cache_creation_input_tokens=getattr(
                        usage_data, "cache_creation_input_tokens", 0
                    ),
                    cache_read_input_tokens=getattr(
                        usage_data, "cache_read_input_tokens", 0
                    ),
                )

        return Message(
            uuid=msg_id,
            role=role,
            content_blocks=content_blocks,
            usage=usage,
            stop_reason=stop_reason,
            timestamp=datetime.now(),
        )
