"""Real-time waste detection engine."""

from __future__ import annotations

import json
import logging
import uuid
from datetime import datetime
from pathlib import Path
from typing import TYPE_CHECKING

from .state import SessionState

if TYPE_CHECKING:
    from ..models import Message
    from .alerts.manager import AlertManager
    from .alerts.models import Alert
    from .detectors.base import PatternDetector

logger = logging.getLogger(__name__)


class RealtimeEngine:
    """Orchestrates real-time pattern detection across sessions."""

    def __init__(
        self,
        detectors: list["PatternDetector"] | None = None,
        alert_manager: "AlertManager" | None = None,
    ):
        """Initialize engine with detectors.

        Args:
            detectors: List of pattern detectors to use. If None, no detectors are active.
            alert_manager: Optional AlertManager for routing alerts. If None, alerts are not routed.
        """
        self.sessions: dict[str, SessionState] = {}
        self.detectors = detectors or []
        self.alert_manager = alert_manager

    def start_session(self, session_id: str | None = None) -> SessionState:
        """Create new session state.

        Args:
            session_id: Optional custom session ID. If None, generates UUID.

        Returns:
            Newly created SessionState object
        """
        if session_id is None:
            session_id = self._generate_session_id()

        if session_id in self.sessions:
            logger.warning(f"Session {session_id} already exists, returning existing")
            return self.sessions[session_id]

        state = SessionState(session_id=session_id)
        self.sessions[session_id] = state
        logger.info(f"Started session {session_id}")
        return state

    def process_message(
        self, session_id: str, message: "Message"
    ) -> list["Alert"]:
        """Process incoming message through all detectors.

        Args:
            session_id: ID of the session
            message: Message to process

        Returns:
            List of alerts generated by all detectors

        Raises:
            KeyError: If session_id not found
        """
        if session_id not in self.sessions:
            raise KeyError(f"Session {session_id} not found")

        state = self.sessions[session_id]

        # Save to JSONL buffer for post-hoc analysis
        state.message_buffer.append(self._message_to_jsonl_dict(message))

        # Update token counts
        if message.usage:
            state.total_output_tokens += message.usage.output_tokens

        # Run all enabled detectors (graceful degradation)
        alerts = []
        for detector in self.detectors:
            try:
                detector_alerts = detector.process_message(message, state)
                alerts.extend(detector_alerts)
            except Exception as e:
                logger.error(
                    f"{detector.__class__.__name__} failed: {e}", exc_info=True
                )
                # Continue with other detectors

        # Store alerts in state
        state.alerts.extend(alerts)

        # Route alerts through AlertManager if available
        if self.alert_manager:
            for alert in alerts:
                try:
                    self.alert_manager.handle_alert(alert, state)
                except Exception as e:
                    logger.error(f"Alert routing failed: {e}", exc_info=True)

        return alerts

    def get_status(self, session_id: str) -> dict:
        """Get current session metrics.

        Args:
            session_id: ID of the session

        Returns:
            Dictionary with current session status

        Raises:
            KeyError: If session_id not found
        """
        if session_id not in self.sessions:
            raise KeyError(f"Session {session_id} not found")

        state = self.sessions[session_id]
        elapsed = datetime.now() - state.start_time

        return {
            "session_id": session_id,
            "elapsed_seconds": elapsed.total_seconds(),
            "waste_percentage": state.waste_percentage(),
            "total_waste_tokens": state.total_waste_tokens,
            "total_output_tokens": state.total_output_tokens,
            "pattern_counts": dict(state.pattern_counts),
            "recent_alerts": [a.to_dict() for a in state.alerts[-5:]],
            "alert_counts_by_severity": state.get_alert_counts_by_severity(),
        }

    def end_session(self, session_id: str, output_dir: Path | None = None) -> Path:
        """Finalize session and return JSONL snapshot path.

        Args:
            session_id: ID of the session to end
            output_dir: Directory to write JSONL snapshot. Defaults to ~/.ter/sessions

        Returns:
            Path to the JSONL snapshot file

        Raises:
            KeyError: If session_id not found
        """
        if session_id not in self.sessions:
            raise KeyError(f"Session {session_id} not found")

        state = self.sessions.pop(session_id)

        # Write JSONL snapshot for post-hoc analysis
        if output_dir is None:
            output_dir = Path.home() / ".ter" / "sessions"

        output_dir.mkdir(parents=True, exist_ok=True)
        snapshot_path = output_dir / f"{session_id}.jsonl"

        with open(snapshot_path, "w") as f:
            for entry in state.message_buffer:
                f.write(json.dumps(entry) + "\n")

        logger.info(f"Ended session {session_id}, snapshot: {snapshot_path}")
        return snapshot_path

    @staticmethod
    def _generate_session_id() -> str:
        """Generate unique session ID."""
        return str(uuid.uuid4())

    @staticmethod
    def _message_to_jsonl_dict(message: "Message") -> dict:
        """Convert Message object to JSONL-compatible dict.

        This matches the format expected by loader.py for post-hoc analysis.
        """
        # Determine message type based on role
        msg_type = message.role  # "user" or "assistant"

        # Build content blocks
        content = []
        for block in message.content_blocks:
            block_dict: dict = {"type": block.block_type}

            if block.text is not None:
                block_dict["text"] = block.text

            if block.tool_name is not None:
                block_dict["name"] = block.tool_name

            if block.tool_input is not None:
                block_dict["input"] = block.tool_input

            if block.tool_use_id is not None:
                if block.block_type == "tool_use":
                    block_dict["id"] = block.tool_use_id
                elif block.block_type == "tool_result":
                    block_dict["tool_use_id"] = block.tool_use_id

            content.append(block_dict)

        # Build message object
        msg = {
            "role": message.role,
            "content": content,
        }

        if message.stop_reason:
            msg["stop_reason"] = message.stop_reason

        # Build usage object
        usage_dict = None
        if message.usage:
            usage_dict = {
                "input_tokens": message.usage.input_tokens,
                "output_tokens": message.usage.output_tokens,
            }
            if message.usage.cache_creation_input_tokens:
                usage_dict["cache_creation_input_tokens"] = (
                    message.usage.cache_creation_input_tokens
                )
            if message.usage.cache_read_input_tokens:
                usage_dict["cache_read_input_tokens"] = (
                    message.usage.cache_read_input_tokens
                )

        if usage_dict:
            msg["usage"] = usage_dict

        # Build top-level entry
        entry = {
            "type": msg_type,
            "uuid": message.uuid,
            "message": msg,
        }

        if message.parent_uuid:
            entry["parentUuid"] = message.parent_uuid

        if message.request_id:
            entry["requestId"] = message.request_id

        if message.timestamp:
            entry["timestamp"] = message.timestamp.isoformat()

        return entry
